# Generated by Django 5.0.6 on 2024-07-07 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AGC",
            fields=[
                ("id_agc", models.AutoField(primary_key=True, serialize=False)),
                (
                    "descripcion_agc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("anio_agc", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Indicador",
            fields=[
                ("id_indicador", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_indicador", models.CharField(max_length=255)),
                (
                    "descripcion_indicador",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fuente", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UGC",
            fields=[
                ("id_ugc", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_ugc", models.CharField(max_length=255)),
                (
                    "descripcion_ugc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "responsable_ugc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fecha_crea_ugc", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AcuerdoIndicadores",
            fields=[
                (
                    "id_acuerdo_indicador",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("valor_min", models.DecimalField(decimal_places=2, max_digits=10)),
                ("valor_opt", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "valor_obtenido",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "peso_indicador",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "resultado_indicador",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "porcentaje_conseguido",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "id_agc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.agc"
                    ),
                ),
                (
                    "id_indicador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.indicador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Objetivo",
            fields=[
                ("id_objetivo", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_objetivo", models.CharField(max_length=255)),
                (
                    "descripcion_objetivo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("perspectiva", models.CharField(max_length=255)),
                (
                    "id_agc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.agc"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="indicador",
            name="id_objetivo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.objetivo"
            ),
        ),
        migrations.AddField(
            model_name="agc",
            name="id_ugc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.ugc"
            ),
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_usuario", models.CharField(max_length=255)),
                (
                    "descripcion_usuario",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("login", models.CharField(max_length=255)),
                ("psw", models.CharField(max_length=255)),
                ("perfil", models.CharField(max_length=255)),
                ("fecha_crea_usuario", models.DateField(blank=True, null=True)),
                (
                    "id_ugc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.ugc"
                    ),
                ),
            ],
        ),
    ]
