# Generated by Django 5.0.6 on 2024-07-07 18:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="objetivo",
            name="id_agc",
        ),
    ]
